name: Java CI with Maven

on:
  push:
    branches:
      - master  # Это означает, что на пуш в ветку main запускается CI.
  pull_request:
    branches:
      - master  # Это означает, что PR в ветку main также будет триггерить CI.

jobs:
  build:
    runs-on: ubuntu-latest  # Это указывает на используемую ОС (здесь - Ubuntu).

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Шаг для скачивания кода из репозитория.

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # или другая JDK (adopt, zulu, corretto и т. д.)
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install  # Компиляция и запуск тестов с помощью Maven.

      - name: Run Tests
        run: mvn test  # Прогон тестов.
      - name: Set up Docker
        run: docker pull jenkins/jenkins:lts  # Загружаем Jenkins образ.

      - name: Run Jenkins container
        run: docker run -d --name jenkins -p 8080:8080 jenkins/jenkins:lts  # Запускаем Jenkins.
